### PR TITLE
almost the last PR!

### PR DESCRIPTION
**Pull request by rachelslaybaugh**
I started at the beginning and made it a good way through. I know I changed a lot, but I really was going with a fine toothed comb. (I had just finished incorporating reviewer edits for a paper from James, so was in the mindset of how pedantic people can be). Lmk what you think and I will try to get through the rest this week. 

Let's make a timeline plan so we don't get merge conflicts. I def can't work on this more before Tuesday night. Not sure if I can then.

### CODE REVIEW

**Comment by kellyrowland** [comment]
I can work on this before Tuesday but then probably not for another week.

I have an interview on the 15th and we have movers booked for the 18th so
the back half of this coming week and the first day or two of the following
week are nuts for me.

I'm on travel (family) the last week of June and first week of July - will
be bringing a laptop but committing to zero work.

**Comment by rachelslaybaugh** [comment]
Ok. Email me when you've done as much as you're going to do and I'll make
sure to pull a clean copy before getting through the rest. I don't think
there's much for you to actively change :)

Good luck with all of it. If it helps, I think I'm visiting 10 cities this
month?

**Comment by kellyrowland** [comment]
Sounds good.

Also, I have to reschedule the July 13 meeting; I have been given a
Jeopardy! contestant audition that morning here (whaaat).

**Comment by rachelslaybaugh** [comment]
Whaaaatttt??? That's the best meeting cancellation reason ever!

**Pull request merged**
